apiVersion: apps/v1
kind: Deployment
metadata:
name: service-a
labels: { app: service-a }
namespace: apps
spec:
replicas: 2
selector:
matchLabels: { app: service-a }
template:
metadata:
labels: { app: service-a }
spec:
imagePullSecrets:
- name: dockerhub-regcred
containers:
- name: service-a
image: jayanth9632932097/service-a:latest
ports:
- containerPort: 3000
readinessProbe:
httpGet: { path: /health, port: 3000 }
initialDelaySeconds: 3
livenessProbe:
httpGet: { path: /health, port: 3000 }
initialDelaySeconds: 10